# Generated by Django 4.2.15 on 2024-08-10 10:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_cliente",
                    models.BooleanField(default=False, verbose_name="cliente status"),
                ),
                (
                    "is_gestore",
                    models.BooleanField(default=False, verbose_name="gestore status"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Campo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipologia", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Campi",
            },
        ),
        migrations.CreateModel(
            name="Impianto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/profile_pics"
                    ),
                ),
                ("numero_campi", models.IntegerField()),
                ("posizione", models.CharField(max_length=255)),
                ("orari", models.CharField(max_length=255)),
                ("prezzi", models.CharField(max_length=100)),
                ("contatti", models.CharField(max_length=100)),
                (
                    "caratteristiche",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Impianti",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
            ],
            options={
                "verbose_name_plural": "Clienti",
            },
        ),
        migrations.CreateModel(
            name="Gestore",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics"),
                ),
            ],
            options={
                "verbose_name_plural": "Gestori",
            },
        ),
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("ora_inizio", models.TimeField()),
                ("ora_fine", models.TimeField()),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.campo"
                    ),
                ),
                (
                    "impianto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.impianto",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prenotazioni",
            },
        ),
        migrations.CreateModel(
            name="Partita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risultato", models.CharField(max_length=50)),
                ("giocatori", models.CharField(max_length=255)),
                (
                    "prenotazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.prenotazione",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Partite",
            },
        ),
        migrations.AddField(
            model_name="campo",
            name="impianto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.impianto"
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                ("descrizione", models.CharField(max_length=501)),
                (
                    "impianto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.impianto",
                    ),
                ),
                (
                    "gestore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.gestore",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
    ]
