# Generated by Django 4.2.15 on 2024-08-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_gestore",
        ),
    ]
