# Generated by Django 4.2.15 on 2024-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_users_is_gestore"),
    ]

    operations = [
        migrations.AddField(
            model_name="impianto",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield", unique=True
            ),
        ),
    ]
