# Generated by Django 4.2.15 on 2024-08-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_impianto_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="impianto",
            name="gestore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.gestore",
            ),
        ),
    ]
