# Generated by Django 4.2.15 on 2024-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_impianto_gestore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impianto",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
