# Generated by Django 4.2.15 on 2024-08-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_cliente_foto_alter_gestore_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prenotazione",
            name="data",
            field=models.DateField(verbose_name=""),
        ),
    ]
