# Generated by Django 4.2.15 on 2024-08-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_prenotazione_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_cliente",
            field=models.BooleanField(default=True, verbose_name="cliente status"),
        ),
    ]
