# Generated by Django 4.2.15 on 2024-08-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_cliente_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="partita",
            name="cliente",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.cliente",
            ),
            preserve_default=False,
        ),
    ]
