# Generated by Django 4.2.15 on 2024-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_news_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="numero",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
