# Generated by Django 4.2.15 on 2024-09-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_remove_cliente_eta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestore",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name_plural": "Utenti"},
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_cliente",
        ),
        migrations.AddField(
            model_name="users",
            name="foto",
            field=models.ImageField(
                blank=True, default="default_profile_pic.png", upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="impianto",
            name="foto",
            field=models.ImageField(
                blank=True, default="default_impianto_photo.jpg", upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="impianto",
            name="gestore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="impianto",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="gestore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="partita",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Gestore",
        ),
    ]
