# Generated by Django 4.2.15 on 2024-12-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_prenotazione_completata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='completata',
        ),
    ]
